### PR TITLE
Zig 0.16 port

### LINKED ISSUE #297: Zig 0.16 branch
Hey there, wanted to use libvaxis with Zig 0.16 (`0.16.0-dev.2261+d6b3dd25a` to be exact), and it seems to be failing to build:
```bash
/Users/burak/.cache/zig/p/uucode-0.1.0-ZZjBPj96QADXyt5sqwBJUnhaDYs_qBeeKijZvlRa0eqM/src/build/tables.zig:339:12: error: invalid builtin function: '@Type'
    return @Type(.{
           ^~~~~
/Users/burak/.cache/zig/p/uucode-0.1.0-ZZjBPj96QADXyt5sqwBJUnhaDYs_qBeeKijZvlRa0eqM/src/build/tables.zig:385:12: error: invalid builtin function: '@Type'
    return @Type(.{
           ^~~~~
/Users/burak/.cache/zig/p/uucode-0.1.0-ZZjBPj96QADXyt5sqwBJUnhaDYs_qBeeKijZvlRa0eqM/src/get.zig:103:16: error: invalid builtin function: '@Type'
    break :blk @Type(.{
               ^~~~~
/Users/burak/.cache/zig/p/uucode-0.1.0-ZZjBPj96QADXyt5sqwBJUnhaDYs_qBeeKijZvlRa0eqM/src/types.zig:539:12: error: invalid builtin function: '@Type'
    return @Type(.{
           ^~~~~
/Users/burak/.cache/zig/p/uucode-0.1.0-ZZjBPj96QADXyt5sqwBJUnhaDYs_qBeeKijZvlRa0eqM/src/types.zig:674:12: error: invalid builtin function: '@Type'
    return @Type(.{
           ^~~~~
/Users/burak/.cache/zig/p/uucode-0.1.0-ZZjBPj96QADXyt5sqwBJUnhaDYs_qBeeKijZvlRa0eqM/src/types.zig:1314:24: error: invalid builtin function: '@Type'
    const InnerUnion = @Type(.{
                       ^~~~~
/Users/burak/.cache/zig/p/uucode-0.1.0-ZZjBPj96QADXyt5sqwBJUnhaDYs_qBeeKijZvlRa0eqM/src/build/Ucd.zig:156:28: error: root source file struct 'fs' has no member named 'cwd'
    const file = try std.fs.cwd().openFile(file_path, .{});
...

```

I can only see errors from the uucode dependency, and it seems like [it has a Zig 0.16 branch](https://github.com/jacobsandlund/uucode/tree/zig-0.16) with fixes as well. Would you be open to having a Zig 0.16 branch with fixes for upcoming breakages? Would be happy to contribute - though seems like the only thing to do is using the 0.16 branch of uucode :)

### PR DESCRIPTION
**Pull request by jcollie**
Port to 0.16. Due to the need to pass a `std.Io` object around APIs have changed a bit.

All examples compile and work. All existing unit tests pass. I'm sure that more changes will be necessary once this starts getting used in anger in real-world applications.

Does not compile on Windows as I lack a system to compile/test on.

Closes #297 #279 #311 #295

### CODE REVIEW

**Comment by lukeflo** [comment]
Great. That looks really good already!

**Comment by jacobsandlund** [comment]
nit: uucode's main is now 0.16 if you want to point to it! 2826a37a4562284fdacd8fa029d49509cc9bffcd

**Comment by ItsMeSamey** [comment]
Hey @jcollie , would you mind taking a look at https://github.com/ItsMeSamey/libvaxis/commit/c22eb29df4653ecd2a49647f528b8a21e64389c0
It includes a few fixes that might help your PR:

- Add -Dllvm as a workound as self hosted backend has a [bug](https://codeberg.org/ziglang/zig/issues/31979) that causes zigimg compilation to segfault.
- Added try's to examples/image.zig `loop.nextEvent()` and mutex operations
- TestTty pipe setup write end was incorrectly using fds[0]; made it fds[1].
- std.process.replace is disallowed after fork() so switched to linux.exec

**Comment by jcollie** [comment]
@ItsMeSamey thanks for those fixes!

File: src/Loop.zig [hunk 1]
```diff
@@ -57,55 +67,84 @@ pub fn Loop(comptime T: type) type {
...
+            SystemResources,
+            Unexpected,
+            Utf8CannotEncodeSurrogateHalf,
+            WouldBlock,
+        };
+
         /// read input from the tty. This is run in a separate thread
-        fn ttyRun(
+        fn ttyRun(self: *Self, paste_allocator: ?std.mem.Allocator) void {
+            self._ttyRun(paste_allocator) catch {};
```
Comment (neurocyte) [inline src/Loop.zig:141]: It would be good to log here to the errors log. Many of the tty errors are potentially end user issues.

File: src/queue.zig [hunk 2]
```diff
@@ -14,32 +13,37 @@ pub fn Queue(
         read_index: usize = 0,
         write_index: usize = 0,
 
-        mutex: std.Thread.Mutex = .{},
+        io: std.Io,
```
Comment (neurocyte) [inline src/queue.zig:16]: In my port to zig-0.16 I decided not to store `io` here to avoid the `io` calls in every push, pop, etc, becoming hidden. I don't think it's really an issue for this PR, but I thought I'd just note it because it kind of goes against the io-as-an-interface design concept.

File: src/queue.zig [hunk 3]
```diff
@@ -14,32 +13,37 @@ pub fn Queue(
...
 
+        pub fn init(io: std.Io) Self {
+            return .{ .io = io };
+        }
+
         /// Pop an item from the queue. Blocks until an item is available.
-        pub fn pop(self: *Self) T {
-            self.mutex.lock();
-            defer self.mutex.unlock();
+        pub fn pop(self: *Self) !T {
```
Comment (neurocyte) [inline src/queue.zig:30]: It seems to me, if we are hiding the `io` by storing the `io` member in `self`, we might as well hide the (or avoid) the new error return values by using `unlockUncancelable` every where. That would greatly reduce the size of the diff caused by `queue` changes.

File: src/tty.zig [hunk 4]
```diff
@@ -43,38 +45,43 @@ pub const PosixTty = struct {
...
+                },
+                .flags = 0,
+            };
+            posix.sigaction(posix.SIG.WINCH, &act, null);
+            handler_io = io;
+            handler_installed = true;
+        }
 
-        const file = std.fs.File{ .handle = fd };
+        // const file = std.fs.File{ .handle = fd };
```
Comment (neurocyte) [inline src/tty.zig]: Why not just delete this?

File: typos.toml [hunk 5]
```diff
@@ -0,0 +1,5 @@
+[default]
```
Comment (neurocyte) [inline typos.toml:1]: Is this file useful? Looks like some sort of linter cruft to me.

File: src/widgets/terminal/Terminal.zig [hunk 6]
```diff
@@ -249,12 +254,16 @@ pub fn get_pty_writer(self: *Terminal) *std.Io.Writer {
...
-fn reader(self: *const Terminal, buf: []u8) std.fs.File.Reader {
-    return self.pty.pty.readerStreaming(buf);
+fn reader(self: *const Terminal, buf: []u8) std.Io.File.Reader {
+    return self.pty.pty.readerStreaming(self.io, buf);
 }
 
 /// process the output from the command on the pty
-fn run(self: *Terminal) !void {
+fn run(self: *Terminal) void {
+    self._run() catch {};
```
Comment (neurocyte) [inline src/widgets/terminal/Terminal.zig:263]: We probably need to log these errors.

**Review by neurocyte — APPROVED** [review]
A really great high quality port. Thanks for this excellent work!

My comments are all minor nitpicks and I don't consider any of them blockers.

File: src/tty.zig (hunk 4 above)
Comment (jcollie) [reply src/tty.zig]: No reason not to, other than I missed that.

File: typos.toml (hunk 5 above)
Comment (jcollie) [reply typos.toml:1]: It's a config file for `typos`, a tool that checks source code for spelling errors. I have it configured to run automatically in my editor, but some projects (like Ghostty) use it in their CI to catch spelling errors in comments etc. It's not necessary, but certainly useful.

File: src/queue.zig (hunk 2 above)
Comment (jcollie) [reply src/queue.zig:16]: I thought about that, but given that allocators are being stored in the structs as well I went ahead and stored the `io` object too. If we're going to have the user pass in the `io` object every time, we should probably do the same for the allocator.

File: src/Loop.zig (hunk 1 above)
Comment (jcollie) [reply src/Loop.zig:141]: I don't like libraries that log, if the user needs to see the error it should be returned as an error and the app developer can choose to log the error or deal with it in some way.

File: src/widgets/terminal/Terminal.zig (hunk 6 above)
Comment (jcollie) [reply src/widgets/terminal/Terminal.zig:263]: See my comments about logging/errors above.

File: src/queue.zig (hunk 3 above)
Comment (jcollie) [reply src/queue.zig:30]: Using `unlockUncancelable` would mean giving up some of the promise of `Io` though wouldn't it? (Though I don't think that we're fulling taking advantage yet).

**Review by ddogfoodd — APPROVED** [review]
I ran the examples and they mostly build and run fine.
`fuzzy` crashes when quitting with ctrl+c and `vt` looks broken, but that might have happened before 0.16 / might be a me problem because of my terminal, screen size etc.

**Comment by rockorager** [comment]
Thanks, @jcollie!

File: src/Loop.zig (hunk 1 above)
Comment (rockorager) [reply src/Loop.zig:141]: I agree with not logging, libvaxis already does some logging but I would like to remove that.
